### ISSUE TITLE
Does it work with self signed certificates

### ISSUE THREAD

**Issue by phoenixtrigo** [Telerik-Verified-Plugins/SecureHTTP-DemoApp#1]
Hi everyone, 

I'm trying to put my phonegap app on iOS making requests with SecureHTTP plugin to a glassfish server with self signed certified installed. Does the plugin work with self signed certificates ? After enable the SSL pining I always got the error function of the get request. I got my .cer files on the www/certificates path.

If anyone know if it's unsuported or got some tip I appreciate .

Thanks in advice

**Comment by EddyVerbruggen** [comment]
Hi,

I don't think your device will like the self signed certificate.. does your browser complain when navigating to the server?

Also, can you extract the log for the exact error the device encounters? On Android you can use `adb logcat` or install the 'CatLog' app from the Play store if that's more convenient.

**Comment by phoenixtrigo** [comment]
Hi again, 
Yes, my browser warns that the page does not have a trusted certificate. Accordingly with that I tried to install the .crt file of my certificate authority on my device and now it works! This file installs a profile on iOS to ensure that certificates are trustable. On android I can´t test it right now. 

Thank you for the answer, it allowed me to reach a solution.

**Comment by EddyVerbruggen** [comment]
Hi, in the past I've done something similar for Android 2 where a GlobalSign root and intermediate cert were not available. That fixed it for me as well. So I'm pretty sure this will fix it on Android as well.

I think this deserves a note in the docs, thx!
