### ISSUE TITLE
SSLPinning Enabled But Localhost communication successfully establishing

### ISSUE THREAD

**Issue by mselmansezgin** [Telerik-Verified-Plugins/SecureHTTP-DemoApp#3]
Hi,

I'm using "Telerik-Verified-Plugins/SecureHTTP" plugin to enable SSLPinning but it seems nothing changed before i enable the SSL pinning. I'm using cordova with an angular web application.
I added plugin to my cordova project successfully.And added .cer file to my cordova project "..\platforms\android\assets"  And called "enableSSLPinning" function in my index-android.html, it gives "SUCCESS, you can now talk only to trusted endpoints" but still i can communicate with my localhost which has no certificate. It is not even a https server.

I am building apk with only "ant". 
**I am wondering to know it(SSLPinning) is checking the ssl certificate for only "cordovaHTTP.get" method which come with this plugin? Or it checks every request from apk to server?**

Any comment(s) would be highly appreciated.
Thanks. 

Here is my index-android.html file code:

```
<script type="text/javascript" src="ios/cordova.js"></script>
<script type="text/javascript">
    document.addEventListener('deviceready', onDeviceReady, false);
    function onDeviceReady() {
        //alert("Device ready");
        console.log("Before SSLPinning Enable");
        window.plugins.CordovaHttpPlugin.enableSSLPinning(
                true, // default false, which allows untrusted connections
                function (msg) {alert("SSLPinning - SUCCESS, you can now talk only to trusted endpoints "+ msg)},
                function (msg) {alert("SSLPinning - ERROR: "   + msg)}
        );
        console.log("After SSLPinning Enable");
    }
</script>
```

here is my build.xml file looks like.

```
<target name="update-url">
        <copy file="www.in/js/index.js"  todir="www/js" overwrite="true"/>
        <replace file="www/js/index.js" token="%APP_URL%" value="${dist.target.url}" />
    </target>
    <target name="update-android">
        <exec executable="${cordova.bin}" vmlauncher="false" failonerror="yes">
            <arg value="platform" />
            <arg value="update" />
            <arg value="android" />
            <env key="ANDROID_HOME" value="${env.ANDROID_HOME}" />
        </exec>
    </target>
    <target name="build-android" depends="update-url">
        <echo message="***** Building APK for target: ${dist.target}" />
        <exec executable="${cordova.bin}" vmlauncher="false" failonerror="yes">
            <arg value="build" />
            <arg value="android" />
            <arg value="--release" />
            <arg value="--" />
            <arg value="--keystore=platforms/android/keystore/release.keystore" />
            <arg value="--storePassword=release" />
            <arg value="--password=release" />
            <arg value="--alias=release" />
            <env key="ANDROID_HOME" value="${env.ANDROID_HOME}" />
        </exec>
    </target>
    <target name="dist-android-env" depends="build-android">
        <copy file="platforms/android/build/outputs/apk/android-release.apk"
              tofile="${dist.dir}/${project.name}-${dist.target}.apk" />
    </target>
    <target name="dist-android" depends="init,update-android">
        <antcall target="dist-android-env">
            <param name="dist.target" value="localhost" />
            <param name="dist.target.url" value="http://192.168.1.108:8080/PRMGUI/index-android.html" />
        </antcall>
    </target>
```

**Comment by EddyVerbruggen** [comment]
What does the code look like that you use to connect to localhost?

**Comment by mselmansezgin** [comment]
Actually i mean "192.168.1.108" with localhost.
This is my computer's local ip. Which runs my angular web app(http://192.168.1.108:8080/PRMGUI/) on tomcat. Apk shows this server as you can see from my build.xml.

In web app "index-android.html" i am enabling SSLPinning.
At cordova side i m using no code for calling localhost. Just build.xml and ip configuration.

**Comment by mselmansezgin** [comment]
At angular side i'm using http post like that 

```
           $http({
                method: "POST",
                url: urlFromConfig,
                params: "",
                data: data,
                headers: {
                    "Content-Type": contentTypeFromConfig
                }
            }
```

**Comment by EddyVerbruggen** [comment]
You **HAVE** to use the plugin for http communication, that's the only way to have SSL Pinning with this plugin.

**Comment by mselmansezgin** [comment]
OK. cordovaHTTP lib has post function but this function has no "data" field, differs from angular's $http.
Any example of post method with data will be very helpful. I have to send data to my server.

```
//This has no data parameter field?
window.cordovaHTTP.post(
  "https://platform.telerik.com",
  {}, // optional params
  {}, // optional headers
  function(msg) {alert("OK: " + msg)},
  function(msg) {alert("ERROR: " + msg)}
);
```

Is this method only for control to url is SSL valid or not, or can i use it just like angular's http library?

**Comment by EddyVerbruggen** [comment]
Have you seen [the example in the readme](https://github.com/Telerik-Verified-Plugins/SecureHTTP#post)?

**Comment by mselmansezgin** [comment]
OK. Thank you for your responses.
One more question:
Even if "assets\www\certificates" has no .cer file(there is no other .cer file in any other folder in apk), plug-in still blocks connection with my server. Is this normal or i'm doing something wrong?

**Comment by EddyVerbruggen** [comment]
If there is no certificate and you enable pinning then yes, those calls should be blocked indeed.
